<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2k22" failures="1" tests="5" name="Testing" time="67.177" errors="0" timestamp="2024-06-20T02:12:55 IST">
  <testcase classname="Com.TestCases.TC_01_Login_to_application" name="verify_TC_01_Login_to_application" time="1.678"/>
  <testcase classname="Com.TestCases.TC_02_Add_items_to_cart_and_verify" name="verify_TC_02_Add_items_to_cart_and_verify" time="1.777"/>
  <testcase classname="Com.TestCases.TC_03_Verify_home_page_demo_tesst_case" name="verify_TC_03_Verify_methods" time="0.652">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at Com.TestCases.TC_03_Verify_home_page_demo_tesst_case.verify_TC_03_Verify_methods(TC_03_Verify_home_page_demo_tesst_case.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- verify_TC_03_Verify_methods -->
  <testcase classname="Com.TestCases.TC_04_Delete_item_from_cart_and_verify_item_removed_successfully" name="verify_TC_04_Delete_item_from_cart_and_verify_item_removed_successfully" time="1.948"/>
  <testcase classname="Com.TestCases.TC_05_Add_one_item_and_place_order" name="verify_TC_04_Delete_item_from_cart_and_verify_item_removed_successfully" time="6.821"/>
</testsuite> <!-- Testing -->
